name: Build and Release APK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.1"
          channel: "stable"
          cache: true

      - name: Create app_secrets.dart file
        run: |
          mkdir -p lib/core/secrets
          cat > lib/core/secrets/app_secrets.dart << 'EOF'
          class AppSecrets {
            static const String supabaseUrl = 'https://placeholder-url.supabase.co';
            static const String supabaseAnnonKey = 'placeholder-anon-key';
          }
          EOF

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Run Flutter analyze
        run: flutter analyze --no-fatal-infos

      - name: Run Flutter tests
        run: flutter test
        continue-on-error: true

      - name: Build APK
        run: flutter build apk --release

      - name: Rename APK with timestamp
        run: |
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/blog-app-$TIMESTAMP.apk
          echo "APK_NAME=blog-app-$TIMESTAMP.apk" >> $GITHUB_ENV

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: blog-app-apk
          path: build/app/outputs/flutter-apk/${{ env.APK_NAME }}
          retention-days: 30

      - name: Create Development Release
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: dev-${{ github.run_number }}
          name: Development Build ${{ github.run_number }}
          body: |
            ## 🛠️ Development Build ${{ github.run_number }}

            **⚠️ This is a development build - use at your own risk**

            ### 📱 Download
            - **APK File**: ${{ env.APK_NAME }}

            ### 🔄 Latest Changes
            ${{ github.event.head_commit.message }}

            ### 🔧 Build Information
            - **Commit**: ${{ github.sha }}
            - **Author**: ${{ github.event.head_commit.author.name }}
            - **Build Date**: ${{ github.event.head_commit.timestamp }}
            - **Flutter Version**: 3.27.1
            - **Dart Version**: 3.6.0

          files: build/app/outputs/flutter-apk/${{ env.APK_NAME }}
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"
        continue-on-error: true

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results.sarif"
        continue-on-error: true
